src/Entity/Faq.php
<?php

namespace App\Entity;

use App\Entity\Contracts\PageInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Faq
 *
 * @ORM\Table(name="faq")
 * @ORM\Entity(repositoryClass="App\Repository\FaqRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Faq implements PageInterface
{
    use Traits\ModifyDateTrait;
    use Traits\SeoTrait;

    public const BASE_PATH = '/faq/';
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="autor", type="string", length=250, nullable=false)
     */
    private $autor;

    /**
     * @var string
     *
     * @ORM\Column(name="text", type="text", length=65535, nullable=false)
     */
    private $text;

    /**
     * @var string
     *
     * @ORM\Column(name="email_autor", type="string", length=250, nullable=false)
     */
    private $emailAutor;

    /**
     * @var int
     *
     * @ORM\Column(name="date", type="integer", nullable=false)
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="otvet_admin", type="text", length=65535, nullable=false)
     */
    private $otvetAdmin;

    /**
     * @var int
     *
     * @ORM\Column(name="count_views", type="integer", nullable=false)
     */
    private $countViews = '0';

    /**
     * @var int
     *
     * @ORM\Column(name="count_like", type="integer", nullable=false)
     */
    private $countLike = '0';

    /**
     * @var int
     *
     * @ORM\Column(name="count_dislike", type="integer", nullable=false)
     */
    private $countDislike = '0';

    /**
     * @ORM\Column(type="boolean")
     */
    private $published = true;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAutor(): ?string
    {
        return $this->autor;
    }

    public function setAutor(string $autor): self
    {
        $this->autor = $autor;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getEmailAutor(): ?string
    {
        return $this->emailAutor;
    }

    public function setEmailAutor(string $emailAutor): self
    {
        $this->emailAutor = $emailAutor;

        return $this;
    }

    public function getDate(): ?int
    {
        return $this->date;
    }

    public function setDate(int $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getOtvetAdmin(): ?string
    {
        return $this->otvetAdmin;
    }

    public function setOtvetAdmin(string $otvetAdmin): self
    {
        $this->otvetAdmin = $otvetAdmin;

        return $this;
    }

    public function getCountViews(): ?int
    {
        return $this->countViews;
    }

    public function setCountViews(int $countViews): self
    {
        $this->countViews = $countViews;

        return $this;
    }

    public function getCountLike(): ?int
    {
        return $this->countLike;
    }

    public function setCountLike(int $countLike): self
    {
        $this->countLike = $countLike;

        return $this;
    }

    public function getCountDislike(): ?int
    {
        return $this->countDislike;
    }

    public function setCountDislike(int $countDislike): self
    {
        $this->countDislike = $countDislike;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getPath(): string
    {
        return self::BASE_PATH . $this->getId() . '/';
    }

    /**
     * @return string|PageInterface
     */
    public function getParent()
    {
        return self::BASE_PATH;
    }

    public function getMetaTitle(): ?string
    {
        if ($this->metaTitle) {
            return $this->metaTitle;
        }
        if ($this->name && $this->autor) {
            return sprintf('Вопрос от %s: %s',$this->autor,$this->name);
        }
        return null;
    }

    public function getMetaDescription(): ?string
    {
        if ($this->metaDescription) {
            return $this->metaDescription;
        }
        if ($this->text) {
            return $this->text;
        }
        return null;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 */
class Service extends Content implements ServiceEntityReedInterface
{
    /**
     * @ORM\ManyToOne(targetEntity="PriceService", inversedBy="contents")
     */
    private $service;

    /**
     * @ORM\ManyToOne(targetEntity="PriceCategory", inversedBy="contents")
     */
    private $price_category;
    

    public function getService(): ?PriceService
    {
        return $this->service;
    }

    public function setService(?PriceService $service): self
    {
        $this->service = $service;

        return $this;
    }
    
    public function getBrandName():string
    {
        $parent = $this->getParent();
        return $parent->getBrandName();
    }
    
    public function getBrandAndModelName():string
    {
        $parent = $this->getParent();
        return $parent->getBrandAndModelName();
    }

    public function getPriceCategory(): ?PriceCategory
    {
        return $this->price_category;
    }

    public function setPriceCategory(?PriceCategory $price_category): self
    {
        $this->price_category = $price_category;

        return $this;
    }
    
    public function getPriceBrand():?PriceBrand
    {
        $parent = $this->getParent();
        if ( ! $parent) {
            return null;
        }
        return $this->getParent()->getPriceBrand();
    }
    
    public function getPriceModel():?PriceModel
    {
        return $this->getParent()->getPriceModel();
    }
    
    public function getBrand():?Brand
    {
        return $this->getParent()->getBrand();
    }
    
    public function getModel():?Model
    {
        return $this->getParent()->getModel();
    }
    
    public function getBrandModelWithTranslation():string
    {
        return $this->getParent()->getBrandModelWithTranslation();
    }
}

templates/v2/blocks/include/contacts.html.twig
<a id="footer_contacts"></a>
<section id="contacts" class="contacts-section">
    <div class="contacts__inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-12">
                    <div class="contacts">
                        <h2 class="contacts__heading">Контакты</h2>
                        <ul class="contacts">
                            <li class="contacts__item">
                                <div class="contacts__icon">
                                    <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                                </div>
                                <div class="contacts__info">

                                    {% if (phone is defined and phone is not null) and (address is defined and address is not null) %}
                                    <p style="line-height: .5">{{ address }}</p>
                                        <p style="line-height: .5"> <span class="phone-number"><a href="tel:{{ phone.value }}">{{ phone.title }}</a></span></p>
                                    {% endif %}

                                </div>
                            </li>
                            <li class="contacts__item">
                                <div class="contacts__icon">
                                    <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                                </div>
                                <div class="contacts__info">
                                    {% if (phone2 is defined and phone2 is not null) and (address2 is defined and address2 is not null) %}
                                        <p style="line-height: .5">{{ address2 }}</p>
                                        <p style="line-height: .5"> <span class="phone-number"><a href="tel:{{ phone2.value }}">{{ phone2.title }}</a></span></p>
                                    {% endif %}

                                </div>
                            </li>
                            <li class="contacts__item">
                                <div class="contacts__icon">
                                    <i class="fas fa-envelope" aria-hidden="true"></i>
                                </div>
                                <div class="contacts__info">
                                    <h6 class="contact__heading">E-mail</h6>
                                    <a href="mailto:info@piksp.ru">vrn@acpik.ru</a>
                                </div>
                            </li>
                            <li class="contacts__item">
                                <div class="contacts__icon">
                                    <i class="far fa-calendar-alt" aria-hidden="true"></i>
                                </div>
                                <div class="contacts__info">
                                    <h6 class="contact__heading">Режим работы</h6>
                                    <p>Ежедневно <br>
                                        с 09:00 до 21:00</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <div id="picsp_map" class="contacts__map">
            <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A16bb8134eb25eb065fd4854d353714dda57f5efbbc8e75ee10a34aef916f1624&amp;width=100%25&amp;height=577&amp;lang=ru_RU&amp;scroll=true"></script>
        </div>

    </div>
</section>

templates/v2/blocks/include/header.html.twig
<header class="container-fluid">
    <div class="container">
        <div class="row header__top-line">
            <div class="col-xs-12 col-sm-12 col-md-3">
                <ul class="header__top-line_left">
                    {% if topMenu is defined and topMenu is not empty %}
                        {% for menuItem in topMenu %}
                            <li><a href="{{ menuItem.link.path }}">{{ menuItem.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-9">
                <ul class="header__top-line_right">
                    {% if models is defined and models is not null %}
                        {% for model in models %}
                            {% if model.nameShort is not null %}
                                <li><a href="/{{ model.code }}">{{ model.nameShort }}</a></li>
                            {% else %}
                            <li><a href="/{{ model.code }}">{{ model.name }}</a></li>
                                {% endif %}
                        {% endfor %}
                    {%  endif %}
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid container_nav">
        <div class="col-1">
            <div class="btn-mobile-menu d-flex justify-content-start">
                <a data-bs-toggle="offcanvas" class="offcanvas__burger" href="#offcanvasMenu" role="button" aria-controls="offcanvasMenu">
                    ☰
                </a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenuLabel">
                    <div class="offcanvas-header">
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close">X</button>
                    </div>
                    <div class="offcanvas-body">
                        <div>
                            <ul class="uk-nav uk-nav-default uk-nav-parent-icon mobile-menu__ul" data-uk-nav="multiple: true">
                                {% for leftMenu_item in leftMenu %}
                                    <li><a href="{{ leftMenu_item.link.path }}">{{ leftMenu_item.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="header__intermediate-wrapper">
            <div class="header__logo">
                <a href="/"><img src="/img/lexus/logo.png" alt="ПИК" width="199" height="44"></a>
            </div>
            <span class="nav__description">Специализированный <br>
                автосервис <span class="nav__description_red">MERCEDES</span> </span>
    {% if (phone is defined and phone is not null) and (address is defined and address is not null) %}
            <div class="nav__address">
                <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                    <div>
                       {{ address }}<br>
                        <a style="display: block" href="tel:{{ phone.value }}">
                            {{ phone.title }}
                        </a>
                    </div>
            </div>
    {% endif %}
            {% if (phone2 is defined and phone2 is not null) and (address2 is defined and address2 is not null) %}
                <div class="nav__address">
                    <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                    <div>
                        {{ address2 }}<br>
                        <a style="display: block" href="tel:{{ phone2.value }}">
                            {{ phone2.title }}
                        </a>
                    </div>
                </div>
            {% endif %}

            <div class="nav__contacts">
                <i class="fas fa-phone" aria-hidden="true"></i>
                <div class="nav__phone">
                    <span class="phone-number"><a href="{% if phone is defined %}tel:{{ phone.value }}{% endif %}">{% if phone is defined %}{{ phone.title }}{% endif %}</a></span>
                    <a class="phone-message" href="javascript:PopUpShow();">Заказать обратный звонок</a>
                </div>
            </div>
            <div class="nav__contacts trubka">
                <a href="tel:+78129159153"><span>
                            <i class="fas fa-phone" aria-hidden="true" style="font-size:40px"></i></span></a>
            </div>
        </div>
    </div>

   {{ include('v2/blocks/include/header_fixed.html.twig') }}
</header>

templates/v2/blocks/include/header_error.html.twig
<header class="container-fluid">
    <div class="container">
        <div class="row header__top-line">
            <div class="col-xs-12 col-sm-12 col-md-3">
                <ul class="header__top-line_left">
                    {% if topMenu is defined and topMenu is not empty %}
                        {% for menuItem in topMenu %}
                            <li><a href="{{ menuItem.link.path }}">{{ menuItem.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-9">
                <ul class="header__top-line_right">
                    {% if brands is not null %}
                        {% for brand in brands %}
                            <li><a href="/{{ brand.code }}">{{ brand.name }}</a></li>
                        {% endfor %}
                    {%  endif %}
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid container_nav">
        <div class="col-1">
            <div class="btn-mobile-menu d-flex justify-content-start">
                <a data-bs-toggle="offcanvas" class="offcanvas__burger" href="#offcanvasMenu" role="button" aria-controls="offcanvasMenu">
                    ☰
                </a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenuLabel">
                    <div class="offcanvas-header">
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close">X</button>
                    </div>
                    <div class="offcanvas-body">
                        <div>
                            <ul class="uk-nav uk-nav-default uk-nav-parent-icon mobile-menu__ul" data-uk-nav="multiple: true">

                                <li><a href="/">Главная</a></li>
                                <li><a href="/offers/">Наши акции</a></li>
                                <li><a href="/blog/">Примеры работ</a></li>
                                <li><a href="/contacts/">Контакты</a></li>

                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="header__intermediate-wrapper">
            <div class="header__logo">
                <a href="/"><img src="/img/lexus/logo.png" alt="ПИК" width="199" height="44"></a>
            </div>
            <span class="nav__description">Специализированный <br>
                автосервис <span class="nav__description_red">MERCEDES</span></span>

            <div class="nav__address">
                <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                <a target="__blank" href="https://yandex.ru/maps/2/saint-petersburg/?um=constructor%3A0b426416135d33a3e9907c055362662e47f0382f0994f673e33c6d4b4799f7f8">г. Москва, <br>
                    ул. Монтажная, д.4"Б" стр.5</a>
            </div>

            <div class="nav__contacts">
                <i class="fas fa-phone" aria-hidden="true"></i>
                <div class="nav__phone">
                    <span class="phone-number"> <span class="phone-number"><a href="tel:+78129159153">+7(812) 915-91-53</a></span></span>
                    <a class="phone-message" href="javascript:PopUpShow();">Заказать обратный звонок</a>
                </div>
            </div>
            <div class="nav__contacts trubka">
                <a href="tel:+78129159153"><span>
                            <i class="fas fa-phone" aria-hidden="true" style="font-size:40px"></i></span></a>
            </div>
        </div>
    </div>

   {{ include('v2/blocks/include/header_fixed.html.twig') }}
</header>

templates/v2/blocks/include/header_fixed.html.twig
{# Меню при скролее #}
<div class="container-fluid container_nav__fixed">

    <div class="col-1">
        <div class="btn-mobile-menu d-flex justify-content-start">
            <a data-bs-toggle="offcanvas" class="offcanvas__burger" href="#offcanvasMenu" role="button" aria-controls="offcanvasMenu">
                ☰
            </a>

            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenuLabel">
                <div class="offcanvas-header">
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close">X</button>
                </div>
                <div class="offcanvas-body">
                    <div>
                        <ul class="uk-nav uk-nav-default uk-nav-parent-icon mobile-menu__ul" data-uk-nav="multiple: true">
                            {% for leftMenu_item in leftMenu %}
                                <li><a href="{{ leftMenu_item.link.path }}">{{ leftMenu_item.name }}</a></li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>




    </div>
    <div class="header__intermediate-wrapper">
        <div class="header__logo">
            {% if logo is defined and logo is not null %}
            <a href="/"><img src="/img/brands/logo/{{ logo }}" alt="ПИК" width="199" height="44"></a>
            {% else %}
            <a href="/"><img src="/img/lexus/logo.png" alt="ПИК" width="199" height="44"></a>
            {% endif %}
        </div>
        <span class="nav__description">Специализированный <br>
            автосервис <span class="nav__description_red">MERCEDES</span>
            </span>

        {% if (phone is defined and phone is not null) and (address is defined and address is not null) %}
            <div class="nav__address">
                <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                <div>
                    {{ address }}<br>
                    <a style="display: block" href="tel:{{ phone.value }}">
                        {{ phone.title }}
                    </a>
                </div>
            </div>
        {% endif %}
        {% if (phone2 is defined and phone2 is not null) and (address2 is defined and address2 is not null) %}
            <div class="nav__address">
                <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                <div>
                    {{ address2 }}<br>
                    <a style="display: block" href="tel:{{ phone2.value }}">
                        {{ phone2.title }}
                    </a>
                </div>
            </div>
        {% endif %}

        <div class="nav__contacts">
            <i class="fas fa-phone" aria-hidden="true"></i>
            <div class="nav__phone">
                <span class="phone-number"><a href="{% if phone is defined %}tel:{{ phone.value }}{% endif %}">{% if phone is defined %}{{ phone.title }}{% endif %}</a></span>
                <a class="phone-message" href="javascript:PopUpShow();">Заказать обратный звонок</a>
            </div>
        </div>
        <div class="nav__contacts trubka">
            <a href="tel:+78129159153"><span>
                            <i class="fas fa-phone" aria-hidden="true" style="font-size:40px"></i></span></a>
        </div>
    </div>
</div>

templates/v2/blocks/include/header_models.html.twig
<header class="container-fluid">
    <div class="container">
        <div class="row header__top-line">
            <div class="col-xs-12 col-sm-12 col-md-3">
                <ul class="header__top-line_left">
                    {% if topMenu is defined and topMenu is not empty %}
                        {% for menuItem in topMenu %}
                            <li><a href="{{ menuItem.link.path }}">{{ menuItem.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-9">
                <ul class="header__top-line_right">
                    {% if models is not null %}
                        {% for model in models %}
                            <li><a href="{{ brandPath }}{{ model.code }}">{{ model.name }}</a></li>
                        {% endfor %}
                    {%  endif %}
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid container_nav">
        <div class="col-1">
            <div class="btn-mobile-menu d-flex justify-content-start">
                <a data-bs-toggle="offcanvas" class="offcanvas__burger" href="#offcanvasMenu" role="button" aria-controls="offcanvasMenu">
                    ☰
                </a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenuLabel">
                    <div class="offcanvas-header">
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close">X</button>
                    </div>
                    <div class="offcanvas-body">
                        <div>
                            <ul class="uk-nav uk-nav-default uk-nav-parent-icon mobile-menu__ul" data-uk-nav="multiple: true">
                                {% for leftMenu_item in leftMenu %}
                                    <li><a href="{{ leftMenu_item.link.path }}">{{ leftMenu_item.name }}</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="header__intermediate-wrapper">
            <div class="header__logo">
                {% if logo is defined and logo is not null %}
                    <a href="/"><img src="/img/brands/logo/{{ logo }}" alt="ПИК" width="199" height="44"></a>
                {% else %}
                    <a href="/"><img src="/img/lexus/logo.png" alt="ПИК" width="199" height="44"></a>
                {% endif %}
            </div>
            <span class="nav__description">Специализированный <br>
                автосервис <span class="nav__description_red">MERCEDES</span>
            </span>

            {% if (phone is defined and phone is not null) and (address is defined and address is not null)%}
                <div class="nav__address">
                    <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                    <div>
                        {{ address }}<br>
                        <a style="display: block" href="tel:{{ phone.value }}">
                            {{ phone.title }}
                        </a>
                    </div>
                </div>
            {% endif %}
            {% if (phone2 is defined and phone2 is not null) and (address2 is defined and address2 is not null) %}
                <div class="nav__address">
                    <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                    <div>
                        {{ address2 }}<br>
                        <a style="display: block" href="tel:{{ phone2.value }}">
                            {{ phone2.title }}
                        </a>
                    </div>
                </div>
            {% endif %}

            <div class="nav__contacts">
                <i class="fas fa-phone" aria-hidden="true"></i>
                <div class="nav__phone">
                    <span class="phone-number"><a href="{% if phone is defined %}tel:{{ phone.value }}{% endif %}">{% if phone is defined %}{{ phone.title }}{% endif %}</a></span>
                    <a class="phone-message" href="javascript:PopUpShow();">Заказать обратный звонок</a>
                </div>
            </div>
            <div class="nav__contacts trubka">
                <a href="tel:+78129159153"><span>
                            <i class="fas fa-phone" aria-hidden="true" style="font-size:40px"></i></span></a>
            </div>
        </div>
    </div>

   {{ include('v2/blocks/include/header_fixed.html.twig') }}
</header>

templates/v2/blocks/include/header_services.html.twig
<header class="container-fluid">
    <div class="container">
        <div class="row header__top-line">
            <div class="col-xs-12 col-sm-12 col-md-3">
                <ul class="header__top-line_left">
                    {% if topMenu is defined and topMenu is not empty %}
                        {% for menuItem in topMenu %}
                            <li><a href="{{ menuItem.link.path }}">{{ menuItem.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-9">
                <ul class="header__top-line_right">
                    {% if popularServices is not null and popularServices is not empty %}
                        {% for service in popularServices %}
                            <li><a href="/{{ service.priceCategory.slug }}/{{ service.slug }}">{{ service.name }}</a></li>
                        {% endfor %}
                    {%  endif %}
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid container_nav">
        <div class="col-1">
            <div class="btn-mobile-menu d-flex justify-content-start">
                <a data-bs-toggle="offcanvas" class="offcanvas__burger" href="#offcanvasMenu" role="button" aria-controls="offcanvasMenu">
                    ☰
                </a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenuLabel">
                    <div class="offcanvas-header">
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close">X</button>
                    </div>
                    <div class="offcanvas-body">
                        <div>
                            <ul class="uk-nav uk-nav-default uk-nav-parent-icon mobile-menu__ul" data-uk-nav="multiple: true">
                                {% for leftMenu_item in leftMenu %}
                                    <li><a href="{{ leftMenu_item.link.path }}">{{ leftMenu_item.name }}</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="header__intermediate-wrapper">
            <div class="header__logo">
                {% if logo is defined and logo is not null %}
                    <a href="/"><img src="/img/brands/logo/{{ logo }}" alt="ПИК" width="199" height="44"></a>
                {% else %}
                    <a href="/"><img src="/img/lexus/logo.png" alt="ПИК" width="199" height="44"></a>
                {% endif %}
            </div>
            <span class="nav__description">Специализированный <br>
                автосервис <span class="nav__description_red">MERCEDES</span>
            </span>

            {% if (phone is defined and phone is not null) and (address is defined and address is not null)%}
                <div class="nav__address">
                    <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                    <div>
                        {{ address }}<br>
                        <a style="display: block" href="tel:{{ phone.value }}">
                            {{ phone.title }}
                        </a>
                    </div>
                </div>
            {% endif %}
            {% if (phone2 is defined and phone2 is not null) and (address2 is defined and address2 is not null) %}
                <div class="nav__address">
                    <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
                    <div>
                        {{ address2 }}<br>
                        <a style="display: block" href="tel:{{ phone2.value }}">
                            {{ phone2.title }}
                        </a>
                    </div>
                </div>
            {% endif %}

            <div class="nav__contacts">
                <i class="fas fa-phone" aria-hidden="true"></i>
                <div class="nav__phone">
                    <span class="phone-number"><a href="{% if phone is defined %}tel:{{ phone.value }}{% endif %}">{% if phone is defined %}{{ phone.title }}{% endif %}</a></span>
                    <a class="phone-message" href="javascript:PopUpShow();">Заказать обратный звонок</a>
                </div>
            </div>
            <div class="nav__contacts trubka">
                <a href="tel:+78129159153"><span>
                            <i class="fas fa-phone" aria-hidden="true" style="font-size:40px"></i></span></a>
            </div>
        </div>
    </div>

   {{ include('v2/blocks/include/header_fixed.html.twig') }}
</header>