src/Entity/Brand.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BrandRepository")
 */
class Brand extends Content
{
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PriceBrand", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="brand_id")
     */
    private $priceBrand;

    public function getBrand(): ?Brand
    {
        return $this;
    }

    public function getModel(): ?Model
    {
        return null;
    }

    public function setPriceBrand(?PriceBrand $brand): self
    {
        $this->priceBrand = $brand;

        return $this;
    }
    
    public function getBrandName():string
    {
        return $this->getPriceBrand()->getName();
    }
    
    public function getBrandAndModelName():string
    {
        return $this->getBrandName();
    }
    
    public function getPriceBrand():?PriceBrand
    {
        return $this->priceBrand;
    }
    
    public function getPriceModel():?PriceModel
    {
        return null;
    }
    
    public function getBrandModelWithTranslation():string
    {
        return $this->getPriceBrand()->getBrandModelWithTranslation();
    }
}

src/Entity/Faq.php
<?php

namespace App\Entity;

use App\Entity\Contracts\PageInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Faq
 *
 * @ORM\Table(name="faq")
 * @ORM\Entity(repositoryClass="App\Repository\FaqRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Faq implements PageInterface
{
    use Traits\ModifyDateTrait;
    use Traits\SeoTrait;

    public const BASE_PATH = '/faq/';
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="autor", type="string", length=250, nullable=false)
     */
    private $autor;

    /**
     * @var string
     *
     * @ORM\Column(name="text", type="text", length=65535, nullable=false)
     */
    private $text;

    /**
     * @var string
     *
     * @ORM\Column(name="email_autor", type="string", length=250, nullable=false)
     */
    private $emailAutor;

    /**
     * @var int
     *
     * @ORM\Column(name="date", type="integer", nullable=false)
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="otvet_admin", type="text", length=65535, nullable=false)
     */
    private $otvetAdmin;

    /**
     * @var int
     *
     * @ORM\Column(name="count_views", type="integer", nullable=false)
     */
    private $countViews = '0';

    /**
     * @var int
     *
     * @ORM\Column(name="count_like", type="integer", nullable=false)
     */
    private $countLike = '0';

    /**
     * @var int
     *
     * @ORM\Column(name="count_dislike", type="integer", nullable=false)
     */
    private $countDislike = '0';

    /**
     * @ORM\Column(type="boolean")
     */
    private $published = true;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAutor(): ?string
    {
        return $this->autor;
    }

    public function setAutor(string $autor): self
    {
        $this->autor = $autor;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getEmailAutor(): ?string
    {
        return $this->emailAutor;
    }

    public function setEmailAutor(string $emailAutor): self
    {
        $this->emailAutor = $emailAutor;

        return $this;
    }

    public function getDate(): ?int
    {
        return $this->date;
    }

    public function setDate(int $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getOtvetAdmin(): ?string
    {
        return $this->otvetAdmin;
    }

    public function setOtvetAdmin(string $otvetAdmin): self
    {
        $this->otvetAdmin = $otvetAdmin;

        return $this;
    }

    public function getCountViews(): ?int
    {
        return $this->countViews;
    }

    public function setCountViews(int $countViews): self
    {
        $this->countViews = $countViews;

        return $this;
    }

    public function getCountLike(): ?int
    {
        return $this->countLike;
    }

    public function setCountLike(int $countLike): self
    {
        $this->countLike = $countLike;

        return $this;
    }

    public function getCountDislike(): ?int
    {
        return $this->countDislike;
    }

    public function setCountDislike(int $countDislike): self
    {
        $this->countDislike = $countDislike;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getPath(): string
    {
        return self::BASE_PATH . $this->getId() . '/';
    }

    /**
     * @return string|PageInterface
     */
    public function getParent()
    {
        return self::BASE_PATH;
    }

    public function getMetaTitle(): ?string
    {
        if ($this->metaTitle) {
            return $this->metaTitle;
        }
        if ($this->name && $this->autor) {
            return sprintf('Вопрос от %s: %s',$this->autor,$this->name);
        }
        return null;
    }

    public function getMetaDescription(): ?string
    {
        if ($this->metaDescription) {
            return $this->metaDescription;
        }
        if ($this->text) {
            return $this->text;
        }
        return null;
    }
}

src/Entity/News.php
<?php

namespace App\Entity;

use App\Entity\Contracts\PageInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class News implements PageInterface
{
    use Traits\ModifyDateTrait;

    public const BASE_PATH = '/news/';
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meta_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meta_description;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     */
    private $sort;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $images;

    /**
     * @ORM\Column(type="text")
     */
    private $short_text;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_views=0;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_like=0;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_dislike=0;

    public function __construct()
    {
        $this->date = time();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(string $meta_title): self
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(string $meta_description): self
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getSort(): ?int
    {
        return $this->sort;
    }

    public function setSort(int $sort): self
    {
        $this->sort = $sort;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function getImagesArray(): ?array
    {
        if ( ! $this->images) {
            return [];
        }
        $images = explode('|',$this->images);
        foreach ($images as &$image) {
            $image =strstr($image,'<<<',true);
        }
        return $images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getShortText(): ?string
    {
        return $this->short_text;
    }

    public function setShortText(string $short_text): self
    {
        $this->short_text = $short_text;

        return $this;
    }

    public function getCountViews(): ?int
    {
        return $this->count_views;
    }

    public function setCountViews(int $count_views): self
    {
        $this->count_views = $count_views;

        return $this;
    }

    public function getCountLike(): ?int
    {
        return $this->count_like;
    }

    public function setCountLike(int $count_like): self
    {
        $this->count_like = $count_like;

        return $this;
    }

    public function getCountDislike(): ?int
    {
        return $this->count_dislike;
    }

    public function setCountDislike(int $count_dislike): self
    {
        $this->count_dislike = $count_dislike;

        return $this;
    }

    public function getDate(): ?int
    {
        return $this->date;
    }

    public function setDate(int $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPath(): ?string
    {
        return self::BASE_PATH . $this->getId() . '/';
    }

    public function getH1(): ?string
    {
        return $this->getName();
    }

    public function getBrandName(): string
    {
        return '';
    }

    /**
     * Возвращает путь из таблицы content или объект PageInterface
     * @return string|PageInterface
     */
    public function getParent()
    {
        return self::BASE_PATH;
    }

    public function getBrandAndModelName(): string
    {
        return '';
    }
}

templates/v2/pages/brand.html.twig
{% extends 'v2/base.html.twig' %}
{% block title %} {{ 'Ремонт '~page.priceBrand.name~'. Автосервис '~page.priceBrand.name~' ПИК в Санкт-Петербурге.' }} {% endblock %}
{% block description %} {% if phone is defined %}{{'Качественный ремонт '~ page.priceBrand.name~' в Санкт-Петербурге. Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта '~page.priceBrand.nameRus~'. Автосервис '~page.priceBrand.name|upper~ ' «ПИК» - ☎ '~phone.value }} {% else%} {{'Качественный ремонт '~ page.priceBrand.name~' в Санкт-Петербурге.Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта '~page.priceBrand.nameRus~'. Автосервис '~page.priceBrand.name|upper~ ' «ПИК» - ☎ '}}{% endif %}{% endblock %}

{% block header_line %}
    {{ include('v2/blocks/include/header_models.html.twig', {models : models ?? null, brandPath, brandName : page.priceBrand.name, logo : page.priceBrand.imgLogo, 'topMenu': topMenu, 'leftMenu': leftMenu}) }}
{% endblock %}
{% block header_banner %}
    {{ include('v2/blocks/section/hero.html.twig',{ h1 : block('h1') ?? page.h1, photoBig : page.priceBrand.photoBig, brandName : page.priceBrand.name }) }}
{% endblock %}

{% block body %}
    {{ include('elements/_content.html.twig') }}
    {{ price_list(page) }}
    {{ brand_models_service(page.priceBrand, page.priceBrand.path) }}
    {{ service_list(page) }}
    {{ include('elements/_advantages.html.twig',{brandName: page.priceBrand.name, 'utpImg': page.priceBrand.utpImg}) }}
    {{ include('elements/_advantages2.html.twig', {brandName: page.priceBrand.name}) }}
    {{ special_offers(page.brandAndModelName) }}
    {{ include('elements/_about_company.html.twig', {brandName: page.priceBrand.name, 'aboutImg': page.priceBrand.aboutImg}) }}

    {% if pageWork is not empty %}
        {% if pageWork is iterable %}
            {{ include('elements/examples.html.twig', {'pageWork' : pageWork[0]}) }}
        {% else %}
            {{ include('elements/examples.html.twig', {'pageWork' : pageWork}) }}
        {% endif %}
    {% endif %}

    {{ include('elements/_quote.html.twig') }}
    {{ include('elements/_team.html.twig', {brandName: page.priceBrand.name}) }}
{% endblock %}

templates/v2/pages/model.html.twig
{% extends 'v2/base.html.twig' %}
{% block title %} {{ 'Ремонт '~page.priceBrand.name~' '~ page.priceModel.name~'. Автосервис '~page.priceBrand.name~' '~ page.priceModel.name~' ПИК в Санкт-Петербурге. '}} {% endblock %}
{% block description %} {% if phone is defined %}{{'Качественный ремонт  '~ page.priceBrand.name~' '~ page.priceModel.name~' в Санкт-Петербурге. Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта '~page.priceBrand.nameRus~' '~ page.priceModel.name~'. Автосервис '~page.priceBrand.name|upper~' '~ page.priceModel.name|upper~ ' «ПИК» - ☎ '~phone.value }} {% else%} {{'Качественный ремонт '~ page.priceBrand.name~' '~ page.priceModel.name~' в Санкт-Петербурге. Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта '~page.priceBrand.nameRus~' '~ page.priceModel.name~'. Автосервис '~page.priceBrand.name|upper~' '~ page.priceModel.name|upper~ ' «ПИК» - ☎ '}}{% endif %}{% endblock %}

{% block header_line %}
    {#{{ include('v2/blocks/include/header_services.html.twig', {'popularServices': popularServices, logo : page.parent.priceBrand.imgLogo, 'topMenu': topMenu, 'leftMenu': leftMenu}) }}#}
    {{ include('v2/blocks/include/header.html.twig', {models : models ?? null, 'topMenu': topMenu, 'leftMenu': leftMenu}) }}
{% endblock %}
{% block header_banner %}
    {{ include('v2/blocks/section/hero.html.twig',{ h1 : block('h1') ?? page.h1, photoBig : page.priceBrand.photoBig, photoModelBig: page.priceModel.photoBig, brandName : page.priceBrand.name, modelName: page.priceModel.name }) }}
{% endblock %}

{% block body %}
    {{ include('elements/_content.html.twig') }}

    <div style="margin: 0 auto 50px auto; display: flex; max-width: 1140px; text-align: center;">
    {{ include('elements/ask_price_form.html.twig') }}
    </div>

    {{ price_list(page) }}
   {# {{ brand_models_service(page.priceBrand, page.priceBrand.path) }}#}
    {{ service_list(page) }}
    {{ include('elements/_advantages.html.twig',{brandName: page.priceBrand.name, modelName: page.priceModel.name, 'utpImg': page.priceBrand.utpImg}) }}
    {{ include('elements/_advantages2.html.twig', {brandName: page.priceBrand.name, modelName: page.priceModel.name}) }}
    {{ special_offers(page.brandAndModelName) }}
    {{ include('elements/_about_company.html.twig', {brandName: page.priceBrand.name, 'aboutImg': page.priceBrand.aboutImg}) }}
    {% if pageWork is not empty %}
        {% if pageWork is iterable %}
            {{ include('elements/examples_model_page.html.twig', {'pageWork' : pageWork, 'modelName': page.priceModel.name}) }}
        {% else %}
            {{ include('elements/examples.html.twig', {'pageWork' : pageWork}) }}
        {% endif %}
    {% endif %}

    {% if video is defined and video is not empty %}
        {{ include('elements/video.html.twig') }}
    {% endif %}

    {{ include('elements/_quote.html.twig') }}
    {{ include('elements/_team.html.twig', {brandName: page.priceBrand.name}) }}
{% endblock %}

templates/v2/pages/recaptcha.html.twig
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
    <div style="font-size: 1.5rem;" class="text-center p-3">
        <div class="container d-flex justify-content-center">
            <div class="row">
                <form method="post">
                    <div class="form-group">
                        <p>Пожалуйста, поставьте галочку и нажмите кнопку Войти</p>
                        <div class="g-recaptcha d-flex justify-content-center" data-sitekey="{{ gg_recaptcha_site_key }}">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Войти</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://www.google.com/recaptcha/api.js"></script>
    </body>
</html>

templates/v2/pages/root-service.html.twig
{% extends 'v2/base.html.twig' %}
{% block title %} {{ page.metaTitle ? page.metaTitle : (page.h1~'. Автосервис Мерседес ПИК') }} {% endblock %}
{% block description %}⭐ ⭐ ⭐ ⭐ ⭐  {{ page.h1 }}. Профильный автосервис Mercedes.  ✅  Заезд день в день!  Цена и стоимость на сайте. ✅ Гарантия.  ✅  Качество. Автосервис «ПИК».{% endblock %}

{% block header_line %}
    {{ include('v2/blocks/include/header.html.twig', {models : models ?? null, 'topMenu': topMenu, 'leftMenu': leftMenu}) }}
{% endblock %}
{% block header_banner %}
    {{ include('v2/blocks/section/hero.html.twig',{ h1 : block('h1') ?? page.h1, 'customH1': page.h1 }) }}
{% endblock %}

{% block body %}
    {{ include('elements/_content.html.twig') }}
    {{ price_list(page) }}
    {#{{ brand_models_service(page.priceBrand, page.priceBrand.path) }}#}
    {#{{ service_list(page) }}#}
    {{ include('elements/_advantages.html.twig') }}
    {{ include('elements/_advantages2.html.twig') }}
    {{ special_offers(page.brandAndModelName) }}
    {{ include('elements/_about_company.html.twig') }}
    {% if pageWork is not empty %}
        {% if pageWork is iterable %}
            {{ include('elements/examples.html.twig', {'pageWork' : pageWork[0]}) }}
        {% else %}
            {{ include('elements/examples.html.twig', {'pageWork' : pageWork}) }}
        {% endif %}
    {% endif %}
    {{ include('elements/_quote.html.twig') }}
    {{ include('elements/_team.html.twig') }}
{% endblock %}

templates/v2/pages/service.html.twig
{% extends 'v2/base.html.twig' %}
{% block title %}{% if page.priceBrand.name is defined and page.priceModel.name is defined%} {{ page.name~' '~page.priceBrand.name~ ' '~ page.priceModel.name~'. Автосервис '~page.priceBrand.name~' ПИК в Санкт-Петербурге.' }} {% elseif page.priceBrand.name is defined %}{{ page.name~' '~page.priceBrand.name~'. Автосервис '~page.priceBrand.name~' ПИК в Санкт-Петербурге' }} {% else %} {{ page.name~' в Санкт-Петербурге.' }}{% endif%} {% endblock %}

{% block description %} {% if phone is defined %}{% if page.priceBrand.name is defined and page.priceModel.name is defined%}{{page.name~' '~ page.priceBrand.name~' '~ page.priceModel.name~' в Санкт-Петербурге.✔ Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта  '~page.priceBrand.nameRus~' '~page.priceModel.nameRus~'. Автосервис '~page.priceBrand.name|upper~'  «ПИК» - ☎ '~phone.value }} {% elseif page.priceBrand.name is defined%} {{page.name~' '~ page.priceBrand.name~' в Санкт-Петербурге.✔ Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта  '~page.priceBrand.nameRus~'. Автосервис '~page.priceBrand.name|upper~ ' «ПИК» - ☎ '~phone.value }} {% else%}{{page.name~' в Санкт-Петербурге.✔ Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта. Автосервис  «ПИК» - ☎ '~phone.value }} {% endif%} {% else%} {% if page.priceBrand.name is defined and page.priceModel.name is defined%}{{page.name~' '~ page.priceBrand.name~' '~ page.priceModel.name~' в Санкт-Петербурге.✔ Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта '~page.priceBrand.nameRus~'. Автосервис '~page.priceBrand.name|upper~' «ПИК» - ☎ '}}{% elseif page.priceBrand.name is defined %}{{page.name~' '~ page.priceBrand.name~' в Санкт-Петербурге.✔ Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта '~page.priceBrand.nameRus~' . Автосервис '~page.priceBrand.name|upper~ ' «ПИК» - ☎ '}}{% else %}{{page.name~' в Санкт-Петербурге.✔ Работаем без выходных 9:00 - 21:00 ✔ Заезд в день обращения ✔ Расчет стоимость ремонта. Профильный автосервис  «ПИК» - ☎ '}}{% endif %}{% endif %}{% endblock %}

{% block header_line %}
    {{ include('v2/blocks/include/header_services.html.twig', {brands : brands ?? null, 'topMenu': topMenu, 'leftMenu': leftMenu, 'popularServices': popularServices}) }}
{% endblock %}
{% block header_banner %}
    {{ include('v2/blocks/section/hero.html.twig',{ h1 : block('h1') ?? page.h1, 'serviceName':page.name, 'photoBig':page.priceBrand.photoBig }) }}
{% endblock %}

{% block body %}
    {{ include('elements/_content.html.twig') }}
    {{ price_list(page) }}
    {% if page.modelId is null %}
        {{ brand_models_service(page.priceBrand, page.priceBrand.path) }}
    {% endif %}
    {{ service_list(page) }}
    {{ include('elements/_advantages.html.twig', {'utpImg': page.priceBrand.utpImg}) }}
    {{ include('elements/_advantages2.html.twig') }}
    {{ special_offers(page.brandAndModelName) }}
    {{ include('elements/_about_company.html.twig',{'aboutImg': page.priceBrand.aboutImg}) }}
    {% if pageWork is not empty %}
        {% if pageWork is iterable %}
            {{ include('elements/examples.html.twig', {'pageWork' : pageWork[0]}) }}
        {% else %}
            {{ include('elements/examples.html.twig', {'pageWork' : pageWork}) }}
        {% endif %}
    {% endif %}
    {{ include('elements/_quote.html.twig') }}
    {{ include('elements/_team.html.twig') }}
{% endblock %}

templates/v2/pages/service_without.html.twig
{% extends 'v2/base.html.twig' %}


{% block body %}
    <div class="container container2">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-lg-12">
                <h1 class="title">{{ page.name }}</h1>
                    <div class="col2 catalog-v2">
                        {{ page.text|raw }}
                    </div>
            </div>
        </div>
    </div>
    {{ special_offers(page.brandAndModelName) }}
    {{ include('elements/_advantages.html.twig') }}

    {{ include('v2/blocks/section/auto-brands.html.twig') }}

{% endblock %}

templates/v2/pages/simple.html.twig
{% extends 'v2/base.html.twig' %}

{% block header_line %}
    {{ include('v2/blocks/include/header.html.twig', {models : models ?? null, 'topMenu': topMenu, 'leftMenu': leftMenu}) }}
{% endblock %}

{% block header_banner %}

    {{ include('v2/blocks/section/hero.html.twig',{ h1 : block('h1') ?? page.h1, 'customH1': page.h1 }) }}
{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block body %}
    {{ include('elements/_content.html.twig', {'page':page}) }}
    {{ price_list(page) }}
    {#{{ brands_service_block() }}#}
    {{ brand_models_service(brand) }}
    {{ service_list(page) }}
    {{ include('elements/_advantages.html.twig') }}
    {{ include('elements/_advantages2.html.twig') }}
    {{ special_offers(page.brandAndModelName) }}
    {{ include('elements/_about_company.html.twig') }}
    {{ include('elements/_quote.html.twig') }}
    {% if video is defined and video is not empty %}
        {{ include('elements/video.html.twig') }}
    {% endif %}
    {{ include('elements/_team.html.twig') }}
{% endblock %}

templates/v2/pages/vacancy.html.twig
{% extends 'v2/base.html.twig' %}

{% block body %}
    {{ include('v2/blocks/section/content.html.twig',{text: page.text }) }}
{% endblock %}